version: "3.7"

services:
  app:
    build:
      context: ./configs/
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - 80:8080
    volumes:
      - ./src:/var/www/html
